### ISSUE TITLE
php-intl does not build (with workaround)

### ISSUE THREAD

**Issue by theCapypara** [wget/archlinux-aur-php70#1]
The intl extension does not build with 7.0.28.

The issue is the same as described in Homebrew/homebrew-php/issues/4831 (sadly I don't have the exact build trace anymore, but it's more or less what's described in the issue).

Adding `export CPPFLAGS="-DU_USING_ICU_NAMESPACE=1"` right before the make command in the PKGBUILD fixes the issue, however I'm not really convinced that's the right solution.

I thought I'd leave this here as an issue, since you seem to "maintain" the current version of PHP7 for the AUR and maybe you know of a better way to fix this

**Comment by wget** [comment]
@Parakoopa Haha. I was *JUST* working on it. Yes, I have a fix for it. It is currently brewing :D 
The patch consists in adding the name space manually to some files. I'm currently porting this 7.1 patch to this 7.0 branch: https://github.com/openwrt/packages/commit/7c0dd7ae879ae627fcbcbb6b675e0b4478787cf5

**Comment by wget** [comment]
And yes, using `-DU_USING_ICU_NAMESPACE=1` is considered bad practise by ICU. ref.: http://source.icu-project.org/repos/icu/trunk/icu4c/readme.html#RecBuild

**Comment by wget** [comment]
@Parakoopa fixed in `master` :)
